"""
database/models.py
──────────────────
SQLite DDL statements for the trading framework.
Every table includes created_at / updated_at timestamps.
"""

SCHEMA_SQL = """
-- ── Strategies registry ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategies (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT    NOT NULL UNIQUE,
    description     TEXT,
    params_json     TEXT,                       -- JSON blob of strategy params
    status          TEXT    NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | PAUSED | RETIRED
    created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ── Signals generated by strategies ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name   TEXT    NOT NULL,
    signal_date     TEXT    NOT NULL,
    signal_type     TEXT    NOT NULL,            -- ENTRY_LONG | EXIT_LONG | ENTRY_SHORT | EXIT_SHORT | NONE
    close_price     REAL,
    indicator_json  TEXT,                        -- JSON blob: SMA200, RSI2, etc.
    meta_json       TEXT,                        -- any extra context
    created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (strategy_name) REFERENCES strategies(name)
);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_name);
CREATE INDEX IF NOT EXISTS idx_signals_date     ON signals(signal_date);

-- ── Trades (entry → exit lifecycle) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name   TEXT    NOT NULL,
    symbol          TEXT    NOT NULL,
    direction       TEXT    NOT NULL,            -- LONG | SHORT
    quantity        INTEGER NOT NULL DEFAULT 1,
    entry_price     REAL,
    entry_time      TEXT,
    exit_price      REAL,
    exit_time       TEXT,
    tp_price        REAL,
    sl_price        REAL,
    atr_entry       REAL,                         -- ATR at entry for stop/target calculations
    bars_held       INTEGER DEFAULT 0,             -- Number of bars held in position
    pnl             REAL,
    status          TEXT    NOT NULL DEFAULT 'OPEN',  -- OPEN | CLOSED | CANCELLED
    created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (strategy_name) REFERENCES strategies(name)
);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy_name);
CREATE INDEX IF NOT EXISTS idx_trades_status   ON trades(status);

-- ── Orders (individual legs of a trade) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id        INTEGER,
    strategy_name   TEXT    NOT NULL,
    symbol          TEXT    NOT NULL,
    action          TEXT    NOT NULL,            -- BUY | SELL
    order_type      TEXT    NOT NULL,            -- LIMIT | STOP | MARKET
    quantity        INTEGER NOT NULL,
    limit_price     REAL,
    stop_price      REAL,
    fill_price      REAL,
    status          TEXT    NOT NULL DEFAULT 'PENDING',  -- PENDING | SUBMITTED | FILLED | CANCELLED
    ib_order_id     INTEGER,
    ib_perm_id      INTEGER,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (trade_id)      REFERENCES trades(id),
    FOREIGN KEY (strategy_name) REFERENCES strategies(name)
);
CREATE INDEX IF NOT EXISTS idx_orders_trade    ON orders(trade_id);
CREATE INDEX IF NOT EXISTS idx_orders_status   ON orders(status);

-- ── Position snapshots (periodic state capture) ────────────────────────────
CREATE TABLE IF NOT EXISTS position_state (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name   TEXT    NOT NULL,
    symbol          TEXT    NOT NULL,
    entry_bar_date  TEXT,
    entry_price     REAL,
    bars_held       INTEGER DEFAULT 0,
    profitable_closes INTEGER DEFAULT 0,
    tp_price        REAL,
    sl_price        REAL,
    state_json      TEXT,                        -- JSON blob for additional state
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (strategy_name) REFERENCES strategies(name),
    UNIQUE(strategy_name, symbol)
);
CREATE INDEX IF NOT EXISTS idx_position_state_strategy ON position_state(strategy_name);
"""
